version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "07:30"
      timezone: America/Chicago
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "07:30"
      timezone: America/Chicago
    groups:
      all-actions:
        patterns:
          - "*"
